spring.application.name=ProjectModurn3
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=ProjectModurn3
spring.datasource.username=postgres
spring.datasource.password=123

# C?u h?nh JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#jwt
jwt.secret-key=tunglx123456bjxbchdbchsdbchsdbchjnjnjsvdsvdsvdsvds
jwt.expired = 90000000

spring.jackson.deserialization.fail-on-unknown-properties=true